<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" ignored="0" total="8" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="1700590" started-at="2023-06-09T09:09:05Z" finished-at="2023-06-09T09:37:25Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="1700590" started-at="2023-06-09T09:09:05Z" finished-at="2023-06-09T09:37:25Z">
      <class name="testscripts.Israel">
        <test-method status="PASS" signature="setUpTestSuite(org.testng.ITestContext)[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestSuite" is-config="true" duration-ms="1769" started-at="2023-06-09T09:09:03Z" finished-at="2023-06-09T09:09:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@13aa6d3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestSuite -->
        <test-method status="FAIL" signature="HomePage_PreLogin_Desktop(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:0, instance:testscripts.Israel@18c1321]" name="HomePage_PreLogin_Desktop" duration-ms="129735" started-at="2023-06-09T09:09:05Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:11:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@1b204a1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Applitools Validation]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Applitools Validation
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.Israel.HomePage_PreLogin_Desktop(Israel.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePage_PreLogin_Desktop -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:09:05Z" finished-at="2023-06-09T09:09:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="FAIL" signature="HomePage_PostLogin_Desktop(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:1, instance:testscripts.Israel@18c1321]" name="HomePage_PostLogin_Desktop" duration-ms="304904" started-at="2023-06-09T09:11:15Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:16:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@3f50e3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Applitools Validation]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Applitools Validation
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.Israel.HomePage_PostLogin_Desktop(Israel.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePage_PostLogin_Desktop -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:11:15Z" finished-at="2023-06-09T09:11:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="FAIL" signature="Therapy_Oncology(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:2, instance:testscripts.Israel@18c1321]" name="Therapy_Oncology" duration-ms="124212" started-at="2023-06-09T09:16:20Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:18:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@11e5514]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verify Navigation List Exist ; Error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verify Navigation List Exist ; Error
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.Israel.Therapy_Oncology(Israel.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Therapy_Oncology -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:16:20Z" finished-at="2023-06-09T09:16:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="FAIL" signature="ContentLibrary_Desktop(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:3, instance:testscripts.Israel@18c1321]" name="ContentLibrary_Desktop" duration-ms="127838" started-at="2023-06-09T09:18:24Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:20:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@90ba07]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Applitools Validation]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Applitools Validation
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.Israel.ContentLibrary_Desktop(Israel.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ContentLibrary_Desktop -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:18:24Z" finished-at="2023-06-09T09:18:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="FAIL" signature="EventsLandingPage_Validation(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:4, instance:testscripts.Israel@18c1321]" name="EventsLandingPage_Validation" duration-ms="60556" started-at="2023-06-09T09:20:32Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:21:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@1e0c179]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Applitools Validation]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Applitools Validation
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.Israel.EventsLandingPage_Validation(Israel.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EventsLandingPage_Validation -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:20:32Z" finished-at="2023-06-09T09:20:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="FAIL" signature="Trodelvy_Desktop(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:5, instance:testscripts.Israel@18c1321]" name="Trodelvy_Desktop" duration-ms="465174" started-at="2023-06-09T09:21:33Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:29:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@1920fb0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verify Navigation List Exist ; Applitools Validation]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verify Navigation List Exist ; Applitools Validation
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.Israel.Trodelvy_Desktop(Israel.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Trodelvy_Desktop -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:21:33Z" finished-at="2023-06-09T09:21:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:29:18Z" finished-at="2023-06-09T09:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="PASS" signature="CIAM_Registration_Field_Validation(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:6, instance:testscripts.Israel@18c1321]" name="CIAM_Registration_Field_Validation" duration-ms="363900" started-at="2023-06-09T09:29:18Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:35:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@dd0fd7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CIAM_Registration_Field_Validation -->
        <test-method status="FAIL" signature="CIAM_Login_SelfServiceFuctionality_Validation(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:7, instance:testscripts.Israel@18c1321]" name="CIAM_Login_SelfServiceFuctionality_Validation" duration-ms="123902" started-at="2023-06-09T09:35:22Z" data-provider="DesktopBrowsers" finished-at="2023-06-09T09:37:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@51180d]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.Israel.CIAM_Login_SelfServiceFuctionality_Validation(Israel.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CIAM_Login_SelfServiceFuctionality_Validation -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.Israel@18c1321]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2023-06-09T09:35:22Z" finished-at="2023-06-09T09:35:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="PASS" signature="tearDownTestSuite()[pri:0, instance:testscripts.Israel@18c1321]" name="tearDownTestSuite" is-config="true" duration-ms="3373" started-at="2023-06-09T09:37:26Z" finished-at="2023-06-09T09:37:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTestSuite -->
      </class> <!-- testscripts.Israel -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
